<?php

namespace Cms\Modules\Product\Tests;

use Cms\Modules\Product\ProductServiceProvider;
use Cms\Modules\Core\Tests\CoreTestCase;

abstract class ProductTestCase extends CoreTestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function getPackageProviders($app): array
    {
        return [
            ProductServiceProvider::class,
        ];
    }

    protected function getEnvironmentSetUp($app)
    {
        // perform environment setup
    }
}

